CREATE SEQUENCE ARTIFACT_ID_SEQ;
CREATE TABLE CF_APPLICATION_ARTIFACT(
    ID BIGINT NOT NULL DEFAULT nextval('ARTIFACT_ID_SEQ'),
    BUILDPACK VARCHAR(4096),
    COMMAND VARCHAR(4096),
    CREATED_AT TIMESTAMP,
    DETECTED_BUILDPACK VARCHAR(4096),
    DETECTED_START_COMMAND VARCHAR(4096),
    DISK_QUOTA BIGINT,
    GUID VARCHAR(1024),
    HEALTH_CHECK_TIMEOUT BIGINT,
    HEALTH_CHECK_TYPE VARCHAR(1024),
    INSTANCES BIGINT,
    MEMORY BIGINT,
    NAME VARCHAR(1024),
    ORGANIZATION VARCHAR,
    SNAPSHOT_ID BIGINT,
    SPACE VARCHAR(1024),
    STATE VARCHAR(1024),
    UPDATED_AT TIMESTAMP,
    VERSION VARCHAR(1024),
    SCOPE VARCHAR(64)
);
ALTER TABLE CF_APPLICATION_ARTIFACT ADD PRIMARY KEY(ID);
ALTER SEQUENCE ARTIFACT_ID_SEQ OWNED BY CF_APPLICATION_ARTIFACT.ID;

CREATE SEQUENCE SNAPSHOT_ID_SEQ;
CREATE TABLE PLATFORM_SNAPSHOT(
    ID BIGINT NOT NULL DEFAULT nextval('SNAPSHOT_ID_SEQ'),
    CREATED_AT TIMESTAMP,
    PLATFORM_VERSION VARCHAR(1024)
);

ALTER TABLE PLATFORM_SNAPSHOT ADD PRIMARY KEY(ID);
ALTER TABLE CF_APPLICATION_ARTIFACT ADD FOREIGN KEY(SNAPSHOT_ID) REFERENCES PLATFORM_SNAPSHOT(ID);
ALTER SEQUENCE SNAPSHOT_ID_SEQ OWNED BY PLATFORM_SNAPSHOT.ID;

