CREATE SEQUENCE ARTIFACT_ID_SEQ;
CREATE TABLE TAP_APPLICATION_ARTIFACT(
    ID BIGINT NOT NULL DEFAULT nextval('ARTIFACT_ID_SEQ'),
    CREATED_AT TIMESTAMP,
    DISK_QUOTA BIGINT,
    GUID VARCHAR(1024),
    INSTANCES BIGINT,
    MEMORY BIGINT,
    NAME VARCHAR(1024),
    SNAPSHOT_ID BIGINT,
    STATE VARCHAR(1024),
    UPDATED_AT TIMESTAMP,
    VERSION VARCHAR(1024),
    IMAGE_ADDRESS VARCHAR(1024),
    URLS VARCHAR(1024),
    CREATED_BY VARCHAR(256),
    UPDATED_BY VARCHAR(256),
    IMAGE_TYPE VARCHAR(256)
);
ALTER TABLE TAP_APPLICATION_ARTIFACT ADD PRIMARY KEY(ID);
ALTER SEQUENCE ARTIFACT_ID_SEQ OWNED BY TAP_APPLICATION_ARTIFACT.ID;

CREATE SEQUENCE SNAPSHOT_ID_SEQ;
CREATE TABLE PLATFORM_SNAPSHOT(
    ID BIGINT NOT NULL DEFAULT nextval('SNAPSHOT_ID_SEQ'),
    CREATED_AT TIMESTAMP,
    PLATFORM_VERSION VARCHAR(1024)
);

ALTER TABLE PLATFORM_SNAPSHOT ADD PRIMARY KEY(ID);
ALTER TABLE TAP_APPLICATION_ARTIFACT ADD FOREIGN KEY(SNAPSHOT_ID) REFERENCES PLATFORM_SNAPSHOT(ID);
ALTER SEQUENCE SNAPSHOT_ID_SEQ OWNED BY PLATFORM_SNAPSHOT.ID;

CREATE INDEX SNAPSHOT_IDX ON PUBLIC.PLATFORM_SNAPSHOT(CREATED_AT);

CREATE SEQUENCE CDH_ARTIFACT_ID_SEQ;
CREATE TABLE CDH_SERVICE_ARTIFACT(
    ID BIGINT NOT NULL DEFAULT nextval('CDH_ARTIFACT_ID_SEQ'),
    NAME VARCHAR(1024),
    TYPE VARCHAR(1024),
    SERVICE_STATE VARCHAR(1024),
    HEALTH_SUMMARY VARCHAR(1024),
    SNAPSHOT_ID BIGINT,
    ENTITY_STATUS VARCHAR(1024)
);
ALTER TABLE CDH_SERVICE_ARTIFACT ADD PRIMARY KEY(ID);
ALTER SEQUENCE CDH_ARTIFACT_ID_SEQ OWNED BY CDH_SERVICE_ARTIFACT.ID;

ALTER TABLE PLATFORM_SNAPSHOT ADD CDH_VERSION VARCHAR(1024);
ALTER TABLE CDH_SERVICE_ARTIFACT ADD FOREIGN KEY(SNAPSHOT_ID) REFERENCES PLATFORM_SNAPSHOT(ID);

ALTER TABLE PLATFORM_SNAPSHOT ADD K8S_VERSION VARCHAR(1024);

CREATE SEQUENCE TAP_SERVICE_ARTIFACT_ID_SEQ;
CREATE TABLE TAP_SERVICE_ARTIFACT(
    ID BIGINT NOT NULL DEFAULT nextval('TAP_SERVICE_ARTIFACT_ID_SEQ'),
    UPDATED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP,
    LABEL VARCHAR(1024),
    DESCRIPTION VARCHAR(4096),
    GUID VARCHAR(1024),
    SNAPSHOT_ID BIGINT
);
ALTER TABLE TAP_SERVICE_ARTIFACT ADD PRIMARY KEY(ID);
ALTER SEQUENCE TAP_SERVICE_ARTIFACT_ID_SEQ OWNED BY TAP_SERVICE_ARTIFACT.ID;

ALTER TABLE TAP_SERVICE_ARTIFACT ADD FOREIGN KEY(SNAPSHOT_ID) REFERENCES PLATFORM_SNAPSHOT(ID);

