CREATE SEQUENCE CDH_ARTIFACT_ID_SEQ;
CREATE TABLE CDH_SERVICE_ARTIFACT(
    ID BIGINT NOT NULL DEFAULT nextval('CDH_ARTIFACT_ID_SEQ'),
    NAME VARCHAR(1024),
    TYPE VARCHAR(1024),
    SERVICE_STATE VARCHAR(1024),
    HEALTH_SUMMARY VARCHAR(1024),
    SNAPSHOT_ID BIGINT,
    ENTITY_STATUS VARCHAR(1024)
);
ALTER TABLE CDH_SERVICE_ARTIFACT ADD PRIMARY KEY(ID);
ALTER SEQUENCE CDH_ARTIFACT_ID_SEQ OWNED BY CDH_SERVICE_ARTIFACT.ID;

ALTER TABLE PLATFORM_SNAPSHOT ADD CDH_VERSION VARCHAR(1024);
ALTER TABLE CDH_SERVICE_ARTIFACT ADD FOREIGN KEY(SNAPSHOT_ID) REFERENCES PLATFORM_SNAPSHOT(ID);