CREATE SEQUENCE CF_SERVICE_ARTIFACT_ID_SEQ;
CREATE TABLE CF_SERVICE_ARTIFACT(
    ID BIGINT NOT NULL DEFAULT nextval('CF_SERVICE_ARTIFACT_ID_SEQ'),
    UPDATED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP,
    LABEL VARCHAR(1024),
    DESCRIPTION VARCHAR(4096),
    GUID VARCHAR(1024),
    SNAPSHOT_ID BIGINT
);
ALTER TABLE CF_SERVICE_ARTIFACT ADD PRIMARY KEY(ID);
ALTER SEQUENCE CF_SERVICE_ARTIFACT_ID_SEQ OWNED BY CF_SERVICE_ARTIFACT.ID;

ALTER TABLE CF_SERVICE_ARTIFACT ADD FOREIGN KEY(SNAPSHOT_ID) REFERENCES PLATFORM_SNAPSHOT(ID);